//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACPMWS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class adAguaInmaculadaPruebaEntities : DbContext
    {
        public adAguaInmaculadaPruebaEntities()
            : base("name=adAguaInmaculadaPruebaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admDocumentos> admDocumentos { get; set; }
        public virtual DbSet<admFoliosDigitales> admFoliosDigitales { get; set; }
        public virtual DbSet<admMovimientos> admMovimientos { get; set; }
    }
}
